name: Build and Release EXE

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write  # Required to create releases and upload assets
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Get latest tag or set default
        id: get_tag
        shell: pwsh
        run: |
          git fetch --tags
          $tag = git describe --tags --abbrev=0 2>$null
          if (-not $tag) {
            $tag = "v0.1.0"
          }
          echo "tag=$tag" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Create new tag (optional)
        id: create_tag
        run: |
          NEW_TAG="v$(date +'%Y.%m.%d.%H%M%S')"
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git tag $NEW_TAG
          git push origin $NEW_TAG

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.create_tag.outputs.new_tag }}
          name: Release ${{ steps.create_tag.outputs.new_tag }}
          files: electron-vue-template-Setup-0.1.0.exe
