name: Build and Release EXE

on:
  push:
    branches:
      - master

jobs:
  version_and_tag:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Bump version and push tag
        run: |
          npm version patch -m "chore(release): %s"
          git push origin HEAD --tags
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# This second job will run on the newly created tag
# Use a separate workflow file: release-on-tag.yml
