name: Auto Bump Version and Tag

on:
  push:
    branches:
      - master

jobs:
  version-bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to push tags and commits

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Bump version and create tag
        id: version
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          # Bump patch version (you can change to minor/major if desired)
          npm version patch -m "chore(release): bump version to %s [skip ci]"
          
          # Push commit and new tag
          git push origin HEAD
          git push origin --tags
