name: Build and Upload EXE to Release

on:
  push:
    branches:
      - master  # or your desired branch

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write  # needed to create releases and upload assets

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project (create .exe)
        run: npm run build  # replace with your build command

      - name: Create or update GitHub Release and upload .exe
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.exe  # update path to your actual .exe
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
