name: Build and Release EXE

on: push

jobs:
  build-project:
    name: Build EXE
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Electron app
        run: npm run build  # This should produce the .exe in dist/

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: electron-exe
          path: dist/*.exe  # Adjust if your .exe file path is different

  release-project:
    name: Release EXE on GitHub
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs: build-project
  
    steps:
      - name: Download EXE artifact
        uses: actions/download-artifact@v4
        with:
          name: electron-exe
  
      - name: Get EXE filename
        id: get_exe
        run: |
          $exe = Get-ChildItem *.exe | Select-Object -ExpandProperty Name
          echo "exe_name=$exe" >> $env:GITHUB_OUTPUT
  
      - name: Create GitHub Release and Upload EXE
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          draft: false
          prerelease: false
          files: ${{ steps.get_exe.outputs.exe_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
