name: Version Bump, Build, and Release

on:
  push:
    branches:
      - master

jobs:
  version-bump-and-release:
    runs-on: windows-latest
    permissions:
      contents: write  # Needed to push tags and create releases

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Bump version and create tag
        id: bump
        shell: pwsh
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
      
          # Bump version and capture output
          $version = npm version patch -m "chore(release): bump version to %s [skip ci]"
          echo "VERSION=$version" >> $env:GITHUB_ENV
      
          git push origin HEAD
          git push origin --tags

      - name: Build and publish with Electron Builder
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run electron:build
